### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by martinopic** [froala/KMSFroalaEditorBundle#42]
It would be useful to have the possibility to manage different configuration profiles and then using them by specifying a "profile" option on the Type.

something like:

```yml
kms_froala_editor:
    profiles:
        profile1:
            tableColors: [ "#FFFFFF", "#FF0000" ]
        profile2:
            tableColors: [ "#FFFF00", "#FF0000" ]
```

and then applying it with

```php
$builder->add( "yourField", FroalaEditorType::class , array('profile' => 'profile1');
```
If you agree with the feature I could provide a pull request for the implementation.
