### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by phillharmonic** [froala/KMSFroalaEditorBundle#66]
I'm using Symfony 4 & Webpack.  Installed per instructions and am getting the above error in the browser's console.  The following statement is throwing the error:

```
<script type="text/javascript">

				$( document ).ready( function () { $( "#field_name" ).froalaEditor({
```
kms_froala_editor.yaml:

```
kms_froala_editor:
    language: "en"
    toolbarInline: true
    tableColors: [ "#FFFFFF", "#FF0000" ]
    saveParams: { "id" : "myEditorField" }    
    includeJQuery: false
    includeCodeMirror: false
    includeFontAwesome: false
    includeJS: false
    includeCSS: false
```

My layout.js that includes the required js:

```
...
'use strict';

import $ from 'jquery';
import 'bootstrap';
import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.css';
import '../css/main.scss';
...
```
A quick scan of the page shows that all javascript files that are required (jquery & froala) are being included.  I suspect it's an issue of "$( document ).ready" being called.  

At any rate, at present am unable to use wysiwyg editor.  Any help would be appreciated.
